### ISSUE TITLE
assert-file operators are wrong

### ISSUE THREAD

**Issue by cornfeedhobo** [jetmartin/bats#18]
I noticed that the `assert_file_exists` and `assert_dir_exists` are not being highlighted correctly. Looking at your tests, I think it's possible that you have these tokens stored as their non-plural form.

**Comment by jetmartin** [comment]
Hi,
Thank you for the feedback.
I’ll check that when back from vacation.
Best.

**Comment by jetmartin** [comment]
Hi,
I've checked, the bats-file functions (from v0.2.0 to v0.4.0) are now much different since the latest release of the VSC plugin.
So it's not a bug but a need of update...
I've anticipated it while fixing the supported release in the Readme.
I assume that maybe others versions have potentially been updated so may should I review all of them.

I'll try to find some time aside of my job to process and test updates.
The bats-file `match` should be completely rebuild for the v0.4.0.
Contributions are always welcome ;)

**Comment by cornfeedhobo** [comment]
Hey, thanks for reviewing this.

I've never contributed to a vscode plugin.. at least that I can remember. If I find some free time I'll see if I can fix this, sure. It would likely be a few months before I can get to it though. I guess we'll see who gets there first! :smile:

**Comment by jetmartin** [comment]
Ok, funny one: 
I've try to re-install bats on my laptop and.... after executing the cmd from the doc

```sh
brew install bats-core
brew tap kaos/shell
brew install bats-support
brew install bats-assert
brew install bats-file
```

I end-up with the previous bats file installed with the previous functions... (v0.3.0)
[Issue is here](https://github.com/kaos/homebrew-shell/blob/master/Formula/bats-file.rb) in the tap.

I have no more time today but must do a PR.

I'm curious, how did you make your install to get the v0.4.0 of bats-file ?

**Comment by cornfeedhobo** [comment]
I'm using bats as a submodule on tests. Here is [an example from bash-trash](https://github.com/cornfeedhobo/bash-trash/blob/main/.gitmodules).

It's confusing because their docs list ways to install bats from system/3rd party repos (e.g. brew), but [the tutorial](https://bats-core.readthedocs.io/en/stable/tutorial.html) shows using it as a submodule instead. I prefer the submodule approach since I want the testing harness to be guaranteed the same for other contributors.

**Comment by jetmartin** [comment]
Hi,

Yes, I use Brew for quick test on my laptop.
A simple `--HEAD` install fix the issue but I need to PR otherwise people using brew will report issues...
In real-life, I will probably have a dedicated bats container used in CI and local devs to ensure consistency.

Side note, in your submodules approach, may should you specify the tag to checkout. Nothings is worst that a failure due to an unexpected dependency update when you're in a rush...

**Comment by cornfeedhobo** [comment]
> Side note, in your submodules approach, may should you specify the tag to checkout. Nothings is worst that a failure due to an unexpected dependency update when you're in a rush...

@jetmartin You're completely right. I noticed that I overlooked pinning to a tag on that repo. Thanks for catching it too!

**Comment by jetmartin** [comment]
Hi,
Ok, code Fixed and retro-compliant.
Works but not really happy with, may should I completely rewrite it.
I need to find some more free time to properly package and publish the update.
Will be available soon.
<img width="414" alt="image" src="https://github.com/jetmartin/bats/assets/6155133/5531c076-6d2b-45cd-b19f-a9734574b843">
<img width="346" alt="image" src="https://github.com/jetmartin/bats/assets/6155133/276eccf3-2620-456f-a8ca-cd4c5c734764">

**Comment by jetmartin** [comment]
Hi,
It's done and updated in both OpenVSX & VSC marketplace.
Best

**Comment by cornfeedhobo** [comment]
Thanks so much for putting in the time on this one. I really appreciate it.
